<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\apps\backend\src\Voytek.Application\Voytek.Application.csproj" />
    <ProjectReference Include="..\..\..\apps\backend\src\Voytek.Domain\Voytek.Domain.csproj" />
    <ProjectReference Include="..\..\..\apps\backend\src\Voytek.SharedKernel\Voytek.SharedKernel.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
