events { }
http {
  upstream voytek_api {
    least_conn;
    server api-1:8080;
    server api-2:8080;
  }
  server {
    listen 8080;
    location / {
      proxy_pass http://voytek_api;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
